<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta description="Star Wars figures shop">
    <link rel="icon" type="img/png" src="img/icon.svg">
    <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="styles/style.css"/>
    <title>FigShop SW</title>
</head>
<body class="d-flex flex-column">
    <?php require_once("views/_header.php"); ?>

    <section class="container-fluid container-sm mt-3 mt-sm-4 mb-3 mb-sm-5 mx-auto d-flex flex-column" id="cartView">
        <h2 class="text-center mb-3">Cart</h2>
        <?php
        $bool = false;
        foreach($cartProducts as $product){
            echo '<div class="cartProduct d-flex align-items-center mb-2 p-1">';
                echo '<img src="img/'.$product->img.'" alt="'.$product->name.'">';
                echo '<p class="mb-0 mx-2 font-weight-bold">'.$product->name.'</p>';
                echo '<p class="mb-0">Quantity: '.$product->quantity.' Price: '.$product->price.'$</p>';
            echo '</div>';
            $bool = true;
        }
        if($bool){
        ?>
        <div class="d-flex justify-content-end">
            <a href="index.php?cart&delete" class="btn btn-danger mr-2">Delete</a>
            <a href="index.php?cart&create" class="btn btn-success">Create order</a>
        </div>
        <?php } ?>
    </section>

    <?php require_once("views/_footer.php"); ?>

    <script src="styles/bootstrap/js/libreriaJquery.js"></script>
    <script src="styles/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>