<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta description="Star Wars figures shop">
    <link rel="icon" type="img/png" src="img/icon.svg">
    <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="styles/style.css"/>
    <title>FigShop SW</title>
</head>
<body class="d-flex flex-column">
    <?php require_once("views/_header.php"); ?>

    <section class="container-fluid container-md mt-3 mt-sm-4 mb-3 mb-sm-5 mx-auto d-flex flex-column" id="adminView">
        <?php echo '<form class="col-12 col-md-8 col-lg-6 p-4 mx-auto" action="index.php?admin-products&edit='.$product->id.'" method="POST">';?>
            <div class="form-group">
                <label for="name">Product name: </label>
                <?php echo '<input type="text" class="form-control" name="name" id="name" value="'.$product->name.'"required>';?>
            </div>
            <div class="form-group">
                <label for="description">Product description: </label>
                <?php echo '<input type="text" class="form-control" name="description" id="description" value="'.$product->description.'"required>';?>
            </div>
            <div class="form-group">
                <label for="image">Image name: </label>
                <?php echo '<input type="text" class="form-control" name="image" id="image" value="'.$product->img.'" required>';?>
            </div>
            <div class="form-group">
                <label for="price">Price: </label>
                <?php echo '<input type="text" class="form-control" name="price" id="price" value="'.$product->price.'" required>';?>
            </div>
            <div class="form-group">
                <label for="quantity">Quantity: </label>
                <?php echo '<input type="text" class="form-control" name="quantity" id="quantity" value="'.$product->quantity.'" required>';?>
            </div>
            <div class="form-group d-flex justify-content-center mt-4 mb-0">
                <input type="submit" class="btn btn-black" name="editProduct" value="Edit product">
            </div>
        </form>
    </section>

    <?php require_once("views/_footer.php"); ?>

    <script src="styles/bootstrap/js/libreriaJquery.js"></script>
    <script src="styles/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>