<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta description="Star Wars figures shop">
    <link rel="icon" type="img/png" src="img/icon.svg">
    <link rel="stylesheet" type="text/css" href="styles/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="styles/style.css"/>
    <title>FigShop SW</title>
</head>
<body class="d-flex flex-column">
    <?php require_once("views/_header.php"); ?>

    <section class="container-fluid container-sm mt-3 mt-sm-4 mb-3 mb-sm-5 mx-auto row d-flex justify-content-center flex-column" id="registerView">
        <h2 class="text-center mb-3">Register</h2>
        <form class="col-12 col-md-8 col-lg-6 p-4 mx-auto" action="index.php?register" method="POST">
            <div class="form-group">
                <label for="name">Name: </label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="form-group">
                <label for="password2">Repeat your password: </label>
                <input type="password" class="form-control" id="password2" name="password2" required>
            </div>
            <div class="form-group">
                <label for="email">Email: </label>
                <input type="email" class="form-control" id="email" name="email" required>
            </div>
            <div class="form-group d-flex justify-content-center mt-4 mb-0">
                <input type="submit" class="btn btn-black" name="register" value="Register">
            </div>
        </form>
    </section>

    <?php require_once("views/_footer.php"); ?>

    <script src="styles/bootstrap/js/libreriaJquery.js"></script>
    <script src="styles/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>